### PR TITLE
New York Times

### PR DESCRIPTION
**Pull request by kelibst**
New York Times
We tried to clone the New York Times website

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### Great job thus far! 🥇 But this project does not look close to the clone. 👇 To consider the project 'complete' it must satisfy the following points:

##### Navigation bar

* [ ] It has a "Hamburger button", a search icon and a link with text on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] It has the NY Times image logo embedded in the center ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] 'Log in' elements on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

##### Main Content

* [ ] It contains centered text and images ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

##### Bottom part

* [ ] It contains links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] It contains links to more popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**Kindly submit for another code review once these have been done.** _Happy coding!_ 🎉

**Comment by kelibst** [comment]
Sorry, I think the style.css file is somehow missing. let us fix that
quickly...

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @kelibst, @Buyaki01, great job with this project:clap:. A few changes and you can :rocket:**

1. Remove all unnecessary files from the project. package.json, package-lock.json and stylint,log aren't required here.

2. Validate your html markup here https://validator.w3.org/#validate_by_upload

3. Enclose the main content of the page in `<main>` tags.

_**You are encouraged to use meaningful & descriptive commit messages in your project**_

_**Kindly make these changes and submit another code review request.**_

**Happy coding:smile:**

**Status: Changes requested**

**Review by mosesogwo — APPROVED** [review]
### :trophy:Great! Project is approved!

You can now merge to master.
You are encouraged to wrap your main content in the `<main>` tags.

**Good luck in your next project:smile:**

**Status: Approved.**

**Comment by Buyaki01** [comment]
We have added the main tag to the body.

**Pull request merged**
